-- 1. What is the total revenue generated by male vs female customers
select gender, sum(purchase_amount) as Revenue
from customers
group by gender;

-- 2. Which customer used a discount but still spend more than average order value
select customer_id, purchase_amount
from customers
where discount_applied = "Yes" AND  purchase_amount >= (select avg(purchase_amount) from customers);

-- 3. which are the top 5 products with the highest average review rating
select item_purchased, round(avg(review_rating),2) as "Average Product Rating"
from customers
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- 4. compare the average purchase amounts between standard and express shipping
select shipping_type, avg(purchase_amount)
from customers
where shipping_type in ("Express", "Standard")
group by shipping_type;

-- 5. Do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
count(customer_id) as "Total Customer", 
sum(purchase_amount) as "Total Revenue", 
avg(purchase_amount) as "Avg Spend"
from customers
group by subscription_status
order by "Total Revenue", "Avg Spend";

-- 6. which 5 products have the highest percentage of purchases with discount applied.
select item_purchased, round((sum(case when discount_applied = "Yes" then 1 else 0 end)/count(*))*100,2) as "discount_rate"
from customers 
group by item_purchased
order by discount_rate desc
limit 5;

-- 7. segment customers into new, returning, loyal based on their previous number of purchases, 
-- and show the count of each segment
with customer_type as (
select customer_id, previous_purchases,
case 
	when previous_purchases = 1 then "New"
    when previous_purchases between 2 and 10 then "Returning"
    else "Loyal" 
    end  as customer_segment
from customers)

select customer_segment, count(customer_id)
from customer_type
group by customer_segment;

-- 8. what are the 3 most purchased product in each catogory
with customer_count as (
select 
	category, 
    item_purchased,
    count(item_purchased) as total_orders,
    row_number() OVER(partition by category order by count(item_purchased) desc) as item_rank
from customers
group by category, item_purchased)

select 
	category, 
    item_purchased,
    total_orders
from customer_count
where item_rank <= 3;

-- 9. are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe
select subscription_status, count(customer_id) as repeat_customers
from customers
where previous_purchases > 5 
group by subscription_status;

-- 10. what is the revenue contribution for each age group
select age_group, sum(purchase_amount)
from customers
group by age_group
order by sum(purchase_amount) desc;

    
